version: "2"
services:
  tsh-stock-api:
    container_name: tsh-stock-api
    build: 
      context: .
      dockerfile: stock_api.dockerfile
    environment:
      FLASK_APP: ${FLASK_APP?:}
      FLASK_ENV: ${FLASK_ENV?:}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST?:}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT?:}
      
      TORN_API_URL: ${TORN_API_URL?:}
      SECRET_KEY: ${SECRET_KEY?:}
      
      DB_PORT: ${DB_PORT?:}
      DB_HOST: ${DB_HOST?:}
      DB_DATABASE: ${DB_DATABASE?:}
      DB_PASS: ${DB_PASS?:}
      DB_USER: ${DB_USER?:}
    depends_on:
      - tsh-stock-db
    ports:
      - "${FLASK_RUN_PORT?:}:${FLASK_RUN_PORT?:}"
    volumes:
      - ./stock_api:/stock_api
      - ./stock_lib:/stock_lib
  tsh-stock-db:
    container_name: tsh-stock-db
    image: mysql:5.7
    ports:
      - "${DB_PORT?:}:${DB_PORT?:}"
    environment:
      MYSQL_ROOT_USER: ${DB_USER?:}
      MYSQL_ROOT_PASSWORD: ${DB_PASS?:}
      MYSQL_HOST: ${DB_HOST?:}
      MYSQL_DATABASE: ${DB_DATABASE?:}
    volumes:
      - tsh-data:/var/lib/mysql
      - ./stock_db/init/:/docker-entrypoint-initdb.d/:ro
  tsh-phpmyadmin:
    container_name: tsh-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - tsh-stock-db
    environment:
      PMA_HOST: ${DB_HOST?:}
      PMA_PORT: ${DB_PORT?:}
    restart: always
    ports:
      - "${PMA_PORT?:}:80"

volumes:
  tsh-data:

