version: "2"
services:
  stock-api:
    container_name: tsh-stock-api
    build: 
      context: .
      dockerfile: stock_api.dockerfile
    environment:
      FLASK_APP: ${FLASK_APP?:}
      FLASK_ENV: ${FLASK_ENV?:}
      FLASK_RUN_HOST: ${FLASK_RUN_HOST?:}
      FLASK_RUN_PORT: ${FLASK_RUN_PORT?:}
      
      SECRET_KEY: ${SECRET_KEY?:}
      
      DB_PORT: ${DB_PORT?:}
      DB_HOST: ${DB_HOST?:}
      DB_DATABASE: ${DB_DATABASE?:}
      DB_PASS: ${DB_PASS?:}
      DB_USER: ${DB_USER?:}
    depends_on:
      - stock-db
    ports:
      - "${FLASK_RUN_PORT?:}:${FLASK_RUN_PORT?:}"
    volumes:
      - ./stock_api:/stock_api
  stock-db:
    container_name: ${DB_HOST?:}
    image: mysql:5.7
    ports:
      - "${DB_PORT?:}:${DB_PORT?:}"
    environment:
      MYSQL_ROOT_USER: ${DB_USER?:}
      MYSQL_ROOT_PASSWORD: ${DB_PASS?:}
      MYSQL_HOST: ${DB_HOST?:}
      MYSQL_DATABASE: ${DB_DATABASE?:}
    volumes:
      - stock-db-mysql:/var/lib/mysql
      - ./stock_db/init/:/docker-entrypoint-initdb.d/:ro
  phpmyadmin:
    container_name: tsh-phpmyadmin
    image: phpmyadmin/phpmyadmin
    depends_on:
      - stock-db
    environment:
      PMA_HOST: ${DB_HOST?:}
      PMA_PORT: ${DB_PORT?:}
    restart: always
    ports:
      - "${PMA_PORT?:}:80"
  stock-worker:
    container_name: tsh-stock-worker
    depends_on:
      - stock-db
    build:
      context: .
      dockerfile: stock_worker.dockerfile
    restart: "no"
    environment:
      TORN_API_URL: ${TORN_API_URL?:}
      TORN_API_KEY: ${TORN_API_KEY?:}
      DB_PORT: ${DB_PORT?:}
      DB_HOST: ${DB_HOST?:}
      DB_DATABASE: ${DB_DATABASE?:}
      DB_PASS: ${DB_PASS?:}
      DB_USER: ${DB_USER?:}
    volumes:
      - stock-worker-logs:/var/log/worker
volumes:
  stock-db-mysql:
  stock-worker-logs:

